### ISSUE TITLE
Zoom Funktion

### ISSUE THREAD

**Issue by Fingadumbledore** [hyperbel/MatheProjekt22_23#12]
**Is your feature request related to a problem? Please describe.**
Es ist noch nicht vorhanden
**Describe the solution you'd like**
2 Buttons pro Funktionsfenster,(+,  -)  diese haben eine Funktion die die Größe des koordinatensystems ändern

**Describe alternatives you've considered**
Es gibt keine Alternative

**Additional context**
Looool

**Comment by hyperbel** [comment]
Nicht ganz fertig, da das graf nicht angezeigt wird! das kann mit #20 verbunden werden, da das die gleiche ursache hat!
